name: Welcome new contributors to the repo

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  welcome-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for creating an issue!"
          pr-message: "Thank you for creating a PR!"
